name: Run OpenID Tests

on: workflow_dispatch

jobs:
  test:
    name: Run Conformance Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          CONFORMANCE_API_TOKEN: ${{secrets.CONFORMANCE_API_TOKEN}}
        run: ./gradlew :test-coordinator:conformanceTests